### ISSUE TITLE
No function

### ISSUE THREAD

**Issue by hartenthaler** [Jefferson49/DownloadGedcomWithURL#1]
I tried to use your module, but it shows no function. I can see on the control panel that it is installed.

http://MY_SUBDOMAIN/index.php?route=/webtrees/DownloadGedcomWithURL/tree/tree1/filename/test shows no error but I would expect to find a .ged file in my download folder. There is none.

http://MY_SUBDOMAIN/index.php?route=/webtrees/DownloadGedcomWithURL/tree/xxxxxxxxxxx/filename/MY_FILENAME
Specifying a wrong tree name "xxxxxxxxx", I would expect to see an error message. There is no error.

**Comment by Jefferson49** [comment]
Thank you for the feedback. Additionally to your URL string, you need to add a privacy level. See also MY_PRIVACY_LEVEL in the readme file. 

For example:
http://MY_SUBDOMAIN/index.php?route=/webtrees/DownloadGedcomWithURL/tree/tree1/filename/test/privacy/user

Since calling some available webtrees API, I do not exactly know, what happens if the tree name is not available.. I simply copied/modified this code section from the existing GedcomExportClient.php. The chosen privacy level is checked for the possible values. Maybe, I will add some checks on the tree name in a future version.

**Comment by hartenthaler** [comment]
I had tested with privacy parameter and without because you had written that there is a default. But my error was that I have to remove webtrees/ in the path because I'm using a subdomain URL and therefore do not need the "webtrees/". So my URL is
`http://xxx/index.php?route=/DownloadGedcomWithURL/tree/tree3/filename/test/privacy/user`
Now it works perfectly. Maybe you can update your README.

**Comment by Jefferson49** [comment]
Issues closed with new release wt2.1v2.0.0
