### ISSUE TITLE
Additional URL parameter

### ISSUE THREAD

**Issue by webtrees-pesz** [Jefferson49/DownloadGedcomWithURL#13]
Is it possible to add an additional URL parameter for an user (MY_USER)?

Based on an user name, the privacy level **and further restrictions for the selected family tree** can be taken into account..

Best regards, Peter

**Comment by Jefferson49** [comment]
Maybe, it would be possible. 

However, let me first explain some of the background: Essentially, the DownloadGedcomWithURL module provides an URL-access to the functionality of the webtrees export in the control panel. Therefore, everything, which is available in the control panel can be used by DownloadGedcomWithURL:

Regarding user access, the control panel offers to run an export as: None (no reatriction), Manager, Member, or Visitor

![Export a Gedcom file](https://github.com/Jefferson49/DownloadGedcomWithURL/assets/81484983/46e17a4e-0411-406c-ba05-88f780e27b98)

Therefore, what you already could do with the current module, is to check the role of the user for a tree (e.g. Manager, Member, or Visitor) and use the role for the parameter MY_PRIVACY_LEVEL.

Maybe, I could add some code to the module, which is automatically doing this check. However, this would only be a small improvement, which might save the time/effort to check the user rights/roles.

Or do you have some other ideas in mind? Can you explain in more detail?

I just found some other area about user rights, which I did not recognize until today: It is possible to specifiy levels to "Restrict to immediate family" in the control panel:

![restrict to immediate family](https://github.com/Jefferson49/DownloadGedcomWithURL/assets/81484983/c2843f89-b374-42c8-bb9a-d99b38a50837)

Do you think in this direction?

Since this feature is not supported by the original webtrees export (see description above), it would be very difficult to implement this.

**Comment by Jefferson49** [comment]
I spent some more thoughts on this topic. One question about introducing a user parameter would be how to priorize user versus privacy level, because  user and privacy level might be inconsistent.

Example:
+ privacy=member
+ user=Anna

URL:
https://MY_URL/webtrees/index.php?route=/webtrees/DownloadGedcomWithURL&key=hYHBiZM9&tree=tree1&privacy=member&user=Anna

What happens if user "Anna" has the role of "Manager"? Do we use the given privacy, which is "Member", or should we use the privacy level assigned to user Anna, which is "Manager".

In general, I hesitate to introduce a user parameter, if the only feature behind that would be to identify the related privacy level (from the user role). That can be done at the time of writing the URL (see above) with little effort.

**Comment by webtrees-pesz** [comment]
Sorry for the late reply.

I made a mistake in my thinking. There is no added value in controlling the GEDCOM export via a separate user.

The background to my considerations is to export a GEDCOM file that is not released to the public with greatly reduced data (BMD - birth/marriage/death) in order to then import it again in a new family tree (for public use) or to make it available as a GEDCOM to a third-party database (MyHeritage, Anchestry, GEDBAS, ...). The whole procedure should ideally be controlled via cron jobs.
The problem, however, is that the event data should be further restricted (only date and place). The dates may only be limited to years. 

Currently I can only hide complete records or facts and events via the privacy restrictions in the family tree, but not parts of them.

The reverse would be ideal. Instead of hiding records, facts and events, the data that are to be transferred are released the other way round.
- INDI.BIRT.DATE
- INDI.BIRT.PLAC
- INDI.FAMC
- INDI.FAMS
- FAM.CHIL
- FAM.HUSB
- FAM.WIFE
- FAM.MARR.DATE
- FAM.MARR.PLAC
...

**Comment by Jefferson49** [comment]
For my own Gedcom files , I apply some "post-processing" after export from webtrees. I am using the [Gedcom Service Programs](https://ofb.hesmer.name/gedserpro_e.html), which offer very sophisticated possiblities to filter and convert Gedcom files. I can imagine that the Gedcom Service Programs might also be suitable for your purposes.

**Comment by webtrees-pesz** [comment]
Thanks for your hints. I do the same with a separate post-processing after export. Today I export the GEDCOM without any restriction and reduce the file remote with my own tool (= GedTool), which is based on Excel macros. If you are interested, send me your contact data to my e-mail address. You will find them in my profile at the webtrees forum (Peter_S). I will send you a full verson for free.
