### ISSUE TITLE
Webtrees can't see the folder to save downloads to

### ISSUE THREAD

**Issue by angelocorbo** [Jefferson49/DownloadGedcomWithURL#14]
Hi,

Installed the latest module release, 3.2.4. Added a subdirectory to the /data directory as suggested by the module (/volume1/web/wt/data/gedcom_backups). 

After getting the warning: "The folder settings could not be saved, because the folder “volume1/web/wt/data/gedcom_backups/” does not exist." I opened a shell to Synology DSM 7.2, sudo su - to elevate rights and found the gedcom_backups directory I created on my Mac was owned by the admin account on Synology (angelocorbo:users). As root changed ownership of the gedcom_backups folder to "http:http" and gave it "777" privs, thinking it would be able to read and write as user http to "volume1/web/wt/data/gedcom_backups/", but no, it's still complaining it can't see it. Any ideas?

Other than that, this module seems a great solution to regular backups. Thank your for the time and effort,

Angelo C.

**Comment by Jefferson49** [comment]
Hi Angelo,

thank you for reporting the issue.

Since other user also reported issues about selecting the folder, I inserted a list with path information in the control panel:

![downloadgedcomwithurl_folders](https://github.com/user-attachments/assets/d9ebc9b8-56ae-4efd-859f-b105cd184f52)

If you open the control panel for the DownloadGedcomWithURL module, it shows the specific path information for your server.

For selecting the DownloadGedcomWithURL folder, you need to provide the **relative path**, typically starting with "data/".

**Comment by angelocorbo** [comment]
Hi there, thank you for the clarification! (should've read the provided info more carefully) and  automating what to me seems critical in any web app, good data backups.

**Comment by Jefferson49** [comment]
Happy to hear that it is working. I will change the text below the folder to be more precise that it is a relative path.
